import { describe, expect, it } from "vitest";
import { AppError } from "../errors";
import { YouTubeRecipeImporter, youtubeTranscriptActorInput } from "./YouTubeRecipeImporter";

describe("YouTubeRecipeImporter", () => {
  it("rejects non-YouTube URLs before calling Apify", async () => {
    const importer = new YouTubeRecipeImporter("token", "actor", ["en", "nl"]);
    await expect(importer.import({ url: "https://example.com/watch?v=1" })).rejects.toBeInstanceOf(AppError);
  });

  it("rejects YouTube channel URLs", async () => {
    const importer = new YouTubeRecipeImporter("token", "actor", ["en", "nl"]);
    await expect(importer.import({ url: "https://www.youtube.com/@someone" })).rejects.toMatchObject({
      code: "validation_error",
    });
  });

  it("sends the video URL and preferred languages to the actor", () => {
    const url = new URL("https://www.youtube.com/shorts/abc123xyz");
    expect(youtubeTranscriptActorInput(url, ["en", "nl"])).toEqual({
      urls: ["https://www.youtube.com/shorts/abc123xyz"],
      outputFormat: "text",
      languages: ["en", "nl"],
      includeAutoGenerated: true,
    });
  });
});
