import { ApifyClient } from "apify-client";
import { detectVideoImportType } from "@savorly/shared";
import type { RecipeSourceImporter, ImportedRecipeSource } from "./types";
import { AppError } from "../errors";
import { parsePublicHttpUrl } from "./ssrfFetch";

type ApifyYoutubeItem = {
  title?: string;
  description?: string;
  channelName?: string;
  channel?: string;
  author?: string;
  captions?: string | { text?: string };
  caption_text?: string;
  fullText?: string;
  transcript?: string;
  text?: string;
  llm?: string;
};

export class YouTubeRecipeImporter implements RecipeSourceImporter<{ url: string }> {
  constructor(
    private readonly token: string,
    private readonly actorId: string,
    private readonly languages: string[],
  ) {}

  async import(input: { url: string }): Promise<ImportedRecipeSource> {
    const url = parsePublicHttpUrl(input.url);
    if (detectVideoImportType(url.href) !== "youtube") {
      throw new AppError("validation_error", "Enter a public YouTube or Shorts URL.", 400);
    }

    const client = new ApifyClient({ token: this.token });
    let run;
    try {
      run = await client.actor(this.actorId).call(youtubeTranscriptActorInput(url, this.languages));
    } catch (error) {
      if (error instanceof AppError) {
        throw error;
      }
      throw new AppError(
        "import_blocked",
        "Could not read this video. Use a public YouTube URL or paste the recipe text instead.",
        502,
        true,
      );
    }

    if (!run?.defaultDatasetId) {
      throw new AppError(
        "import_blocked",
        "YouTube did not return caption data. Paste the recipe text instead.",
        422,
        true,
      );
    }

    const { items } = await client.dataset(run.defaultDatasetId).listItems();
    const item = (items[0] ?? {}) as ApifyYoutubeItem;
    const caption = item.description ?? item.title ?? "";
    const transcript = pickYoutubeTranscript(item);
    const extractedText = [caption, transcript].filter(Boolean).join("\n\n");

    if (!extractedText) {
      throw new AppError(
        "import_blocked",
        "This video has no description or transcript. Paste the recipe text instead.",
        422,
        true,
      );
    }

    return {
      sourceType: "youtube",
      originalUrl: url.href,
      sourceName: "YouTube",
      author: item.channelName || item.channel || item.author,
      caption: caption || undefined,
      transcript: transcript || undefined,
      extractedText,
    };
  }
}

export function youtubeTranscriptActorInput(url: URL, languages: string[]) {
  return {
    urls: [url.href],
    outputFormat: "text",
    languages,
    includeAutoGenerated: true,
  };
}

function pickYoutubeTranscript(item: ApifyYoutubeItem): string {
  if (typeof item.captions === "string") {
    return item.captions;
  }
  if (item.captions && typeof item.captions.text === "string") {
    return item.captions.text;
  }
  return item.caption_text ?? item.fullText ?? item.transcript ?? item.text ?? item.llm ?? "";
}
